import { chromium } from '@playwright/test';
const out = process.env.SHOTS;
const browser = await chromium.launch();
const page = await browser.newPage({ locale: 'tr-TR', viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, hasTouch: true });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
await page.goto('http://localhost:5173/');
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/01-title.png` });
await page.getByText('Yeni Macera').click();
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/02-mode.png` });
await page.getByText('Klasik', { exact: true }).click();
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/03-class.png` });
await page.getByText('Maceraya Atıl').click();
await page.waitForTimeout(600);
await page.screenshot({ path: `${out}/04-map.png` });
await page.locator('.mnode.avail').first().click({ force: true });
await page.waitForTimeout(1500);
await page.screenshot({ path: `${out}/05-battle.png` });
const ok = page.locator('.hint-box .btn');
if (await ok.count()) await ok.click();
// select first playable card
await page.locator('.hand .card').first().click({ force: true });
await page.waitForTimeout(300);
await page.screenshot({ path: `${out}/06-selected.png` });
console.log('errors:', JSON.stringify(errors, null, 1));
await browser.close();
