/**
 * 12x12 original pixel icons. 'a' = main tint, 'b' = shade, 'c' = highlight;
 * other letters use BASE_PALETTE.
 */
export const ICONS: Record<string, string[]> = {
  sword: [
    '..........ww',
    '.........wlw',
    '........wlw.',
    '.......wlw..',
    '......wlw...',
    '.....wlw....',
    '..y.wlw.....',
    '...ylw......',
    '...yy.......',
    '..n.yy......',
    '.n...y......',
    'n...........',
  ],
  shield: [
    '............',
    '..aaaaaaaa..',
    '.acccaaaaab.',
    '.accaayaaab.',
    '.acaayyyaab.',
    '.aaayyyyyab.',
    '.aaaayyyaab.',
    '..aaaayaab..',
    '..aaaaaabb..',
    '...aaaabb...',
    '....abbb....',
    '.....bb.....',
  ],
  axe: [
    '............',
    '....aaa.....',
    '...acaaa....',
    '..acaaaan...',
    '..aaaaan....',
    '...aaan.....',
    '.....n......',
    '....n.......',
    '...n........',
    '..n.........',
    '.n..........',
    '............',
  ],
  hammer: [
    '............',
    '...aaaaaa...',
    '..acccaaab..',
    '..aaaaaaab..',
    '...bbnbbb...',
    '.....n......',
    '.....n......',
    '.....n......',
    '.....n......',
    '.....N......',
    '.....N......',
    '............',
  ],
  dagger: [
    '............',
    '.........w..',
    '........wl..',
    '.......wl...',
    '......wl....',
    '.....wl.....',
    '...y.l......',
    '....y.......',
    '...ny.y.....',
    '..n.........',
    '.n..........',
    '............',
  ],
  daggers: [
    '............',
    '..w......w..',
    '..lw....wl..',
    '...lw..wl...',
    '....lwwl....',
    '.....ll.....',
    '....y..y....',
    '...y....y...',
    '..n......n..',
    '.n........n.',
    '............',
    '............',
  ],
  bow: [
    '....nn......',
    '.....nn...l.',
    '......n..l..',
    '......nnl...',
    '.......n....',
    '...wwwwlwwa.',
    '.......n....',
    '......nnl...',
    '......n..l..',
    '.....nn...l.',
    '....nn......',
    '............',
  ],
  arrow: [
    '............',
    '.........aa.',
    '........aaa.',
    '.......aaa..',
    '......nn....',
    '.....nn.....',
    '....nn......',
    '...nn.......',
    '.wnn........',
    '.ww.........',
    'ww..........',
    '............',
  ],
  arrows: [
    '............',
    '..aa.aa.aa..',
    '..a..a..a...',
    '..n..n..n...',
    '..n..n..n...',
    '..n..n..n...',
    '..n..n..n...',
    '..w..w..w...',
    '.w.ww.ww.w..',
    '............',
    '............',
    '............',
  ],
  fist: [
    '............',
    '...aaaaa....',
    '..acaacaa...',
    '..aaaaaaab..',
    '..acaacaab..',
    '..aaaaaaab..',
    '...aaaaabb..',
    '...aaaaab...',
    '....aaab....',
    '....aaab....',
    '....bbbb....',
    '............',
  ],
  boot: [
    '............',
    '...aaaa.....',
    '...acaa.....',
    '...aaaa.....',
    '...aaaa.....',
    '...aaaa.....',
    '...aaaaa....',
    '...aaaaaaa..',
    '...aaaaaaab.',
    '...bbbbbbbb.',
    '............',
    '............',
  ],
  fire: [
    '.....y......',
    '....yy......',
    '....yfy..y..',
    '...yffy.yy..',
    '..yfffyyfy..',
    '..yffrffffy.',
    '.yffrrrfffy.',
    '.yfrrRrrffy.',
    '.yfrRRRrffy.',
    '..yfrRrrfy..',
    '...yffffy...',
    '....yyyy....',
  ],
  ice: [
    '.....u......',
    '...u.u.u....',
    '....uuu.....',
    '.u..uwu..u..',
    '..uuwwwuu...',
    'uuwwwwwwwuu.',
    '..uuwwwuu...',
    '.u..uwu..u..',
    '....uuu.....',
    '...u.u.u....',
    '.....u......',
    '............',
  ],
  lightning: [
    '......yyy...',
    '.....yyy....',
    '....yyy.....',
    '...yyy......',
    '..yyyyyy....',
    '....yyy.....',
    '...yyy......',
    '..yyy.......',
    '.yyy........',
    '.yy.........',
    '.y..........',
    '............',
  ],
  drop: [
    '.....a......',
    '.....a......',
    '....aaa.....',
    '....aaa.....',
    '...aacaa....',
    '..aacaaaa...',
    '..acaaaaa...',
    '..aaaaaab...',
    '..aaaaabb...',
    '...abbbb....',
    '....bbb.....',
    '............',
  ],
  skull: [
    '............',
    '...wwwwww...',
    '..wwwwwwww..',
    '..wwwwwwww..',
    '..wkkwwkkw..',
    '..wkkwwkkw..',
    '..wwwkkwww..',
    '...wwwwww...',
    '...wkwkwk...',
    '...wwwwww...',
    '............',
    '............',
  ],
  heart: [
    '............',
    '..rr...rr...',
    '.rwrr.rrrr..',
    '.rwrrrrrrrR.',
    '.rrrrrrrrrR.',
    '.rrrrrrrrrR.',
    '..rrrrrrrR..',
    '...rrrrrR...',
    '....rrrR....',
    '.....rR.....',
    '............',
    '............',
  ],
  sun: [
    '.....y......',
    '..y..y..y...',
    '...y.y.y....',
    '....yyy.....',
    '.y.yYYYy.y..',
    'yyyyYYYyyyy.',
    '.y.yYYYy.y..',
    '....yyy.....',
    '...y.y.y....',
    '..y..y..y...',
    '.....y......',
    '............',
  ],
  moon: [
    '............',
    '....aaaa....',
    '...aaa......',
    '..aaa.......',
    '..aa........',
    '..aa........',
    '..aa........',
    '..aaa.......',
    '...aaa...a..',
    '....aaaaa...',
    '............',
    '............',
  ],
  eye: [
    '............',
    '............',
    '...aaaaaa...',
    '..awwwwwwa..',
    '.awwkkkwwwa.',
    'awwkkekkwwwa',
    '.awwkkkwwwa.',
    '..awwwwwwa..',
    '...aaaaaa...',
    '............',
    '............',
    '............',
  ],
  star: [
    '.....y......',
    '.....y......',
    '....yyy.....',
    '....yyy.....',
    'yyyyywyyyyy.',
    '.yyyywyyyy..',
    '..yyyyyyy...',
    '...yyyyy....',
    '..yyy.yyy...',
    '..yy...yy...',
    '.y.......y..',
    '............',
  ],
  gear: [
    '.....aa.....',
    '..a.aaaa.a..',
    '..aaaaaaaa..',
    '..aaabbaaa..',
    '.aaab..baaa.',
    'aaab....baaa',
    'aaab....baaa',
    '.aaab..baaa.',
    '..aaabbaaa..',
    '..aaaaaaaa..',
    '..a.aaaa.a..',
    '.....aa.....',
  ],
  bomb: [
    '.........yf.',
    '........y...',
    '.......n....',
    '.....kkk....',
    '...kkkkkkk..',
    '..kkwkkkkkk.',
    '..kwkkkkkkk.',
    '..kkkkkkkkk.',
    '..kkkkkkkkk.',
    '...kkkkkkk..',
    '....kkkkk...',
    '............',
  ],
  trap: [
    '............',
    '............',
    '.l.l.l.l.l..',
    '.ll.lll.ll..',
    '.lllllllll..',
    '.dddddddddd.',
    '.d........d.',
    '.lllllllll..',
    '.ll.lll.ll..',
    '.l.l.l.l.l..',
    '............',
    '............',
  ],
  spikes: [
    '............',
    '............',
    '..l...l...l.',
    '..l...l...l.',
    '.lll.lll.lll',
    '.lll.lll.lll',
    'lllllllllllll',
    'ddddddddddd.',
    'dddddddddd..',
    '............',
    '............',
    '............',
  ],
  chain: [
    '............',
    '.aa.........',
    'a..a........',
    'a..aaa......',
    '.aaa..a.....',
    '...a..aaa...',
    '....aaa..a..',
    '......a..aaa',
    '.......aaa..',
    '..........a.',
    '............',
    '............',
  ],
  wind: [
    '............',
    '.......aaa..',
    '..........a.',
    '.aaaaaaaaaa.',
    '............',
    '..aaaaaaaa..',
    '..........a.',
    '.aaaaaaaaa..',
    '............',
    '...aaaaa....',
    '........a...',
    '.......a....',
  ],
  book: [
    '............',
    '..bbbbbbbb..',
    '.baaaaaaaab.',
    '.baayyyyaab.',
    '.baaaaaaaab.',
    '.baayyyaaab.',
    '.baaaaaaaab.',
    '.baaaaaaaab.',
    '.bwwwwwwwwb.',
    '.bbbbbbbbbb.',
    '............',
    '............',
  ],
  crystal: [
    '.....a......',
    '....aca.....',
    '...acaab....',
    '...acaab....',
    '..acaaabb...',
    '..acaaabb...',
    '..aaaaabb...',
    '...aaabb....',
    '...aaabb....',
    '....abb.....',
    '.....b......',
    '............',
  ],
  coin: [
    '............',
    '...yyyyy....',
    '..yYYYYYy...',
    '.yYyyyyyYy..',
    '.yYyYYYyYy..',
    '.yYyYyyyYy..',
    '.yYyYYYyYy..',
    '.yYyyyYyYy..',
    '.yYyYYYyYy..',
    '..yYYYYYy...',
    '...yyyyy....',
    '............',
  ],
  potion: [
    '....nnn.....',
    '....lll.....',
    '.....l......',
    '....lal.....',
    '...laaal....',
    '..laacaal...',
    '..lacaaal...',
    '..laaaaal...',
    '..lbaaabl...',
    '...lbbbl....',
    '....lll.....',
    '............',
  ],
  ring: [
    '....aaa.....',
    '...acaa.....',
    '....aa......',
    '...yyyy.....',
    '..yY..Yy....',
    '.yY....Yy...',
    '.y......y...',
    '.yY....Yy...',
    '..yY..Yy....',
    '...yyyy.....',
    '............',
    '............',
  ],
  feather: [
    '..........a.',
    '........aaa.',
    '.......acaa.',
    '......acaab.',
    '.....acaab..',
    '....acaab...',
    '...acaab....',
    '...aaab.....',
    '..abbb......',
    '..n.........',
    '.n..........',
    '............',
  ],
  dice: [
    '............',
    '..wwwwwwww..',
    '.wwwwwwwwwl.',
    '.wkwwwwwkwl.',
    '.wwwwwwwwwl.',
    '.wwwwkwwwwl.',
    '.wwwwwwwwwl.',
    '.wkwwwwwkwl.',
    '.wwwwwwwwwl.',
    '..llllllll..',
    '............',
    '............',
  ],
  mask: [
    '............',
    '..aaaaaaaa..',
    '.aaaaaaaaaa.',
    '.akkaaaakka.',
    '.akkaaaakka.',
    '.aaaaaaaaaa.',
    '..aaakkaaa..',
    '..aaaaaaaa..',
    '...akkkka...',
    '....aaaa....',
    '............',
    '............',
  ],
  hourglass: [
    '..nnnnnnnn..',
    '...wwwwww...',
    '...wyyyyw...',
    '....wyyw....',
    '.....ww.....',
    '.....yw.....',
    '....wyyw....',
    '...wyyyyw...',
    '...wyyyyw...',
    '..nnnnnnnn..',
    '............',
    '............',
  ],
  crown: [
    '............',
    '............',
    '.y...y...y..',
    '.yy.yyy.yy..',
    '.yyyyyyyyy..',
    '.yrYyuyYry..',
    '.yyyyyyyyy..',
    '.YYYYYYYYY..',
    '............',
    '............',
    '............',
    '............',
  ],
  bag: [
    '............',
    '....nnn.....',
    '.....n......',
    '...aaaaa....',
    '..aaaaaaa...',
    '.aaaayaaab..',
    '.aaayyyaab..',
    '.aaaayaaab..',
    '.aaaaaaabb..',
    '..abbbbbb...',
    '............',
    '............',
  ],
  scroll: [
    '............',
    '.nnnnnnnnn..',
    '.nwwwwwwwn..',
    '..wkkkkkw...',
    '..wwwwwww...',
    '..wkkkkww...',
    '..wwwwwww...',
    '..wkkkkkw...',
    '.nwwwwwwwn..',
    '.nnnnnnnnn..',
    '............',
    '............',
  ],
  wall: [
    '............',
    '.aaa.aaa.aa.',
    '.bbb.bbb.bb.',
    '...aa.aaa.a.',
    '...bb.bbb.b.',
    '.aaa.aaa.aa.',
    '.bbb.bbb.bb.',
    '...aa.aaa.a.',
    '...bb.bbb.b.',
    '.aaa.aaa.aa.',
    '.bbb.bbb.bb.',
    '............',
  ],
  cloud: [
    '............',
    '............',
    '.....aaa....',
    '...aaaaaaa..',
    '..aaacaaaaa.',
    '.aacaaaaaaab',
    '.aaaaaaaaaab',
    '..abbbbbbbb.',
    '...a..a..a..',
    '..a..a..a...',
    '............',
    '............',
  ],
  soul: [
    '............',
    '.....aa.....',
    '....aaaa....',
    '...aaccaa...',
    '...acwwca...',
    '...acwwca...',
    '...aaccaa...',
    '....aaaa....',
    '.....aaa....',
    '......aa....',
    '.......a....',
    '............',
  ],
  bone: [
    '............',
    '.ww.........',
    'wwww........',
    '.wwww.......',
    '...www......',
    '....www.....',
    '.....www....',
    '......www...',
    '.......wwww.',
    '........wwww',
    '.........ww.',
    '............',
  ],
  target: [
    '............',
    '....aaaa....',
    '...a....a...',
    '..a.aaaa.a..',
    '.a.a....a.a.',
    '.a.a.aa.a.a.',
    '.a.a.aa.a.a.',
    '.a.a....a.a.',
    '..a.aaaa.a..',
    '...a....a...',
    '....aaaa....',
    '............',
  ],
  wave: [
    '............',
    '............',
    '....aaa.....',
    '..aa...a....',
    '.a......a...',
    '.a.aaa...a..',
    '..a...aa..a.',
    '.a.......a..',
    '.aaaaaaaaa..',
    '............',
    '............',
    '............',
  ],
  leaf: [
    '..........a.',
    '.......aaaa.',
    '.....aacaaa.',
    '....acaaab..',
    '...acaaab...',
    '..acaaab....',
    '..aaaab.....',
    '..aabb......',
    '.nbb........',
    'n...........',
    '............',
    '............',
  ],
  rune: [
    '............',
    '....aaaa....',
    '...a....a...',
    '..a..cc..a..',
    '.a..c..c..a.',
    '.a...cc...a.',
    '.a..c..c..a.',
    '..a..cc..a..',
    '...a....a...',
    '....aaaa....',
    '............',
    '............',
  ],
  wolf: [
    '............',
    '..a......a..',
    '..aa....aa..',
    '..aaaaaaaa..',
    '..aeaaaaea..',
    '..aaaaaaaa..',
    '...aaaaaa...',
    '...aawwaa...',
    '....akka....',
    '.....aa.....',
    '............',
    '............',
  ],
  turret: [
    '............',
    '............',
    '....aaa.....',
    '...aaaaabbb.',
    '...aayaabbb.',
    '...aaaaa....',
    '....bbb.....',
    '...bbbbb....',
    '..aaaaaaa...',
    '..bbbbbbb...',
    '.aaaaaaaaa..',
    '............',
  ],
  lotus: [
    '............',
    '.....a......',
    '....aca.....',
    '....aaa.....',
    '.a..aaa..a..',
    '.aa.aaa.aa..',
    '.aaaaaaaaa..',
    '..aaaaaaa...',
    '...aaaaa....',
    '.ggggggggg..',
    '............',
    '............',
  ],
  claw: [
    '............',
    '.w...w...w..',
    '.w...w...w..',
    '.ww..ww..ww.',
    '..w...w...w.',
    '..ww..ww..ww',
    '...w...w...w',
    '...ww..ww..w',
    '....w...w...',
    '............',
    '............',
    '............',
  ],
  blood: [
    '.....r......',
    '.....r......',
    '....rrr.....',
    '....rrr.....',
    '...rrwrr....',
    '..rrwrrrr...',
    '..rwrrrrr...',
    '..rrrrrrR...',
    '..rrrrrRR...',
    '...rRRRR....',
    '....RRR.....',
    '............',
  ],
  explosion: [
    '..y.....y...',
    '...y.y.y....',
    '.y.yfffy.y..',
    '..yfrrrfy...',
    'yyfrryrrfyy.',
    '..yfrrrfy...',
    '.y.yfffy.y..',
    '...y.y.y....',
    '..y.....y...',
    '............',
    '............',
    '............',
  ],
  campfire: [
    '.....f......',
    '....fyf.....',
    '...fyyf.f...',
    '...fyyyff...',
    '..ffyyyyff..',
    '..fyyryyyf..',
    '...frrrrf...',
    '.nn.NNNN.nn.',
    '..nnNNNNnn..',
    '.nn......nn.',
    '............',
    '............',
  ],
  chest: [
    '............',
    '..nnnnnnnn..',
    '.nNNNNNNNNn.',
    '.nNnnnnnnNn.',
    '.yyyyyyyyyy.',
    '.nnnnyynnnn.',
    '.nNNNyyNNNn.',
    '.nNNNNNNNNn.',
    '.nNNNNNNNNn.',
    '.yyyyyyyyyy.',
    '............',
    '............',
  ],
  question: [
    '............',
    '...aaaaa....',
    '..aa...aa...',
    '..aa...aa...',
    '.......aa...',
    '......aa....',
    '.....aa.....',
    '.....aa.....',
    '............',
    '.....aa.....',
    '.....aa.....',
    '............',
  ],
  elite: [
    '.a........a.',
    '.aa......aa.',
    '..aaaaaaaa..',
    '..wwwwwwww..',
    '..wrrwwrrw..',
    '..wrrwwrrw..',
    '..wwwkkwww..',
    '...wwwwww...',
    '...wkwkwk...',
    '....wwww....',
    '............',
    '............',
  ],
  boss: [
    '.y...y...y..',
    '.yy.yyy.yy..',
    '.yyyyyyyyy..',
    '..wwwwwww...',
    '.wrrwwwrrw..',
    '.wrrwwwrrw..',
    '.wwwwkwwww..',
    '..wwwwwww...',
    '..wkwkwkw...',
    '...wwwww....',
    '............',
    '............',
  ],
  shop: [
    '............',
    '....nnn.....',
    '...n...n....',
    '..yyyyyyy...',
    '.yyyyyyyyy..',
    '.yyyykyyyy..',
    '.yyykkkyyy..',
    '.yyyykyyyy..',
    '.yyyyyyyYY..',
    '..YYYYYYY...',
    '............',
    '............',
  ],
  energy: [
    '....yyyyy...',
    '...yyyyy....',
    '..yyyyy.....',
    '..yyyyyyyy..',
    '.....yyyy...',
    '....yyyy....',
    '...yyy......',
    '..yyy.......',
    '..yy........',
    '..y.........',
    '............',
    '............',
  ],
  cards: [
    '............',
    '...aaaaaa...',
    '..baaaaaab..',
    '.bwwwwwwwb..',
    '.bwaaaaawb..',
    '.bwaaaaawb..',
    '.bwaaaaawb..',
    '.bwaaaaawb..',
    '.bwwwwwwwb..',
    '.bbbbbbbbb..',
    '............',
    '............',
  ],
  lock: [
    '............',
    '....llll....',
    '...l....l...',
    '...l....l...',
    '..yyyyyyyy..',
    '..yYYYYYYy..',
    '..yYYkkYYy..',
    '..yYYkkYYy..',
    '..yYYYYYYy..',
    '..yyyyyyyy..',
    '............',
    '............',
  ],
  trophy: [
    '............',
    '.yyyyyyyyy..',
    'y.yyyyyyy.y.',
    'y.yywyyyy.y.',
    '.yyywyyyyy..',
    '...yyyyy....',
    '....yyy.....',
    '.....y......',
    '....yyy.....',
    '...YYYYY....',
    '............',
    '............',
  ],
  map: [
    '............',
    '.nnnnnnnnnn.',
    '.nwwwwwwwwn.',
    '.nwwrwwwwwn.',
    '.nwwwrwwwwn.',
    '.nwwwwrrwwn.',
    '.nwwwwwwrwn.',
    '.nwwwwwwkwn.',
    '.nwwwwwwwwn.',
    '.nnnnnnnnnn.',
    '............',
    '............',
  ],
  slime: [
    '............',
    '............',
    '............',
    '.....aa.....',
    '...aaaaaa...',
    '..aacaaaaa..',
    '..acaaaaaa..',
    '.aakaaakaab.',
    '.aaaaaaaaab.',
    '.bbbbbbbbbb.',
    '............',
    '............',
  ],
  stars: [
    '............',
    '..y.....y...',
    '.yyy...yyy..',
    '..y.....y...',
    '............',
    '.....y......',
    '....yyy.....',
    '.....y......',
    '............',
    '...y.....y..',
    '..yyy...yyy.',
    '...y.....y..',
  ],
  crack: [
    '............',
    '..aaaaaaaa..',
    '.aaa.aaaaab.',
    '.aaaa.aaaab.',
    '.aaa.aaaaab.',
    '.aaaa.aaaab.',
    '..aa.a.aab..',
    '..aaaa.aab..',
    '...aa.abb...',
    '....abbb....',
    '............',
    '............',
  ],
  bear: ['............', '.aa......aa.', '.abaaaaaaba.', '..aaaaaaaa..', '.aaekaakeaa.', '.aaaaaaaaaa.', '.aaaccccaaa.', '..aackkcaa..', '...aaccaa...', '....aaaa....', '............', '............'],
  drum: ['............', '.n........n.', '..n......n..', '..wwwwwwww..', '.wllllllllw.', '.aaaaaaaaaa.', '.ayayayayaa.', '.aaaaaaaaaa.', '.ayayayayaa.', '.aaaaaaaaaa.', '..bbbbbbbb..', '............'],
  bottle: ['.....nn.....', '.....ll.....', '.....ll.....', '....laal....', '...laaaal...', '...lacaal...', '...lcaaal...', '...laaaal...', '...laaaal...', '...lbbbbl...', '....llll....', '............'],
  cannon: ['............', '............', '.......kkkk.', '.....kkkkkkk', '...kkkwkkkkk', '..kkkkkkkk..', '.kkkkkkkk...', '..nnnnnnn...', '.nNNnnnNNn..', '.NnnN..NnnN.', '..NN....NN..', '............'],
  parrot: ['............', '.....rrr....', '....rrkryy..', '....rrrrry..', '...urrrr....', '..uuyrrr....', '.uuyyrrr....', '..uuyrr.....', '....rrr.....', '.....uu.....', '....u..u....', '............'],
  anchor: ['.....aa.....', '....a..a....', '.....aa.....', '..aaaaaaaa..', '.....aa.....', '.....aa.....', '.....aa.....', '.a...aa...a.', '.aa..aa..aa.', '..aa.aa.aa..', '...aaaaaa...', '............'],
  pistol: ['............', '............', '.kkkkkkkkkk.', '.kllllllllk.', '.kkkkkkkkkk.', '.....nnnkk..', '....nnnnk...', '...nnnn.....', '..nnnn......', '..nnn.......', '............', '............'],
  spear: ['..........w.', '.........wl.', '........wll.', '.......nll..', '......nn....', '.....nn.....', '....nn......', '...nn.......', '..nn........', '.nn.........', 'nn..........', '............'],
  tentacle: ['.......aa...', '......aaca..', '......abb...', '.....aab....', '.....ab.....', '....aab.....', '....ab......', '....aab.....', '.....aab....', '..kkkaabkk..', '.kkkkkkkkkk.', '............'],
  tree: ['....gggg....', '..gggGgggg..', '.ggGgggggGg.', '.gggggGgggg.', '..gGgggggg..', '....gnng....', '.....nn.....', '.....nn.....', '.....nn.....', '....nnnn....', '...N....N...', '............'],
  totem: ['..a......a..', '..aaaaaaaa..', '...akaaka...', '...aaaaaa...', '...akkkka...', '....aaaa....', '...bbbbbb...', '...bayyab...', '...bbbbbb...', '....aaaa....', '...nnnnnn...', '............'],
};

/** aliases so data can use descriptive names */
export const ICON_ALIAS: Record<string, string> = {
  charge: 'boot',
  hurl: 'fist',
  shieldBash: 'shield',
  roar: 'wave',
  quake: 'explosion',
  fang: 'claw',
  banner: 'star',
  whirl: 'wind',
  net: 'chain',
  snow: 'ice',
  poisonArrow: 'arrow',
  bolt: 'lightning',
  fireball: 'fire',
  iceWall: 'wall',
  spark: 'lightning',
  blink: 'star',
  fireRing: 'fire',
  meteor: 'explosion',
  echo: 'wave',
  cloak: 'moon',
  poisonDagger: 'dagger',
  shadow: 'moon',
  smoke: 'cloud',
  needle: 'dagger',
  skullDagger: 'skull',
  holy: 'sun',
  pray: 'sun',
  scales: 'shield',
  nova: 'sun',
  shadowBolt: 'soul',
  drain: 'soul',
  scythe: 'skull',
  golem: 'skull',
  grave: 'skull',
  wrench: 'hammer',
  plate: 'shield',
  mine: 'bomb',
  barrel: 'bomb',
  magnet: 'chain',
  steam: 'cloud',
  drone: 'gear',
  detonator: 'bomb',
  rocket: 'arrow',
  tesla: 'lightning',
  mech: 'gear',
  stance: 'shield',
  kick: 'boot',
  dragon: 'fire',
  fists: 'fist',
  gem: 'crystal',
  bandage: 'heart',
  rock: 'wall',
  swap: 'wind',
  whetstone: 'sword',
  curse: 'skull',
  worm: 'drop',
  weak: 'crack',
  shieldBroken: 'crack',
  ki: 'lotus',
  lantern: 'soul',
  beads: 'ring',
  lamp: 'fire',
  compass: 'map',
  orb: 'crystal',
  belt: 'bag',
  seal: 'coin',
  mirror: 'shield',
  hook: 'chain',
  chalice: 'potion',
  scale: 'shield',
  pickaxe: 'hammer',
  idol: 'crown',
  well: 'drop',
  anvil: 'hammer',
  altar: 'skull',
  peddler: 'bag',
  mushroom: 'cloud',
  adventurer: 'sword',
  spring: 'drop',
  cauldron: 'potion',
  dummy: 'target',
  battle: 'sword',
  event: 'question',
  rest: 'campfire',
  treasure: 'chest',
  settings: 'gear',
  deck: 'cards',
  sound: 'wave',
  acid: 'drop',
  web: 'chain',
  impact: 'explosion',
  vine: 'leaf',
  beam: 'eye',
  summon: 'skull',
};

export function iconRows(id: string): string[] {
  return ICONS[id] ?? ICONS[ICON_ALIAS[id]] ?? ICONS.question;
}
