/**
 * Original pixel art, authored as character grids.
 * '.' = transparent. Letters map to colours (see BASE_PALETTE), and
 * a/b/c/e/h/s/m can be overridden per unit to create variants.
 * All sprites face RIGHT; enemies are mirrored at render time.
 */

export const BASE_PALETTE: Record<string, string> = {
  k: '#1a1020',
  w: '#f4f1e8',
  l: '#c3c8d4',
  d: '#4a4e5e',
  m: '#a4adbf',
  M: '#6b7385',
  s: '#f2c29b',
  S: '#c98e6b',
  r: '#c83838',
  R: '#8a2230',
  y: '#f5d442',
  Y: '#c79a2a',
  n: '#8a5a34',
  N: '#5a3820',
  g: '#5fb04a',
  G: '#35702a',
  u: '#4f8ad9',
  U: '#2f5a9e',
  p: '#8e5bd6',
  P: '#5e3494',
  f: '#ff8a2a',
  F: '#c4561a',
  t: '#4fe0c8',
  T: '#2f8a7e',
  // overridable defaults
  a: '#9aa3b5',
  b: '#6b7385',
  c: '#454b5c',
  e: '#ff4d4d',
  h: '#7a5230',
};

export interface SpriteDef {
  rows: string[];
  palette?: Record<string, string>;
}

export const SPRITES: Record<string, SpriteDef> = {
  /* ------------------------------------------------------------ heroes */
  'hero:warrior': {
    rows: [
      '................',
      '.......rr.......',
      '......rMMM......',
      '.....MmmmmM.....',
      '.....mmkmkm.....',
      '.....mmmmmm..l..',
      '......MssM...l..',
      '....RrrmmrrR.l..',
      '...uuRrrrrrR.l..',
      '..uyyuRrrrrsyyy.',
      '..uyyuRrrrr..n..',
      '..uuuuRYYYR.....',
      '...uu.MM.MM.....',
      '......MM.MM.....',
      '.....NNN.NNN....',
      '................',
    ],
  },
  'hero:ranger': {
    palette: { a: '#7a5a3a', b: '#4f3a26', c: '#2e5a3a', h: '#1f3f28' },
    rows: [
      '................',
      '......bbbb...n..',
      '.....baaaab...n.',
      '....baaSssb...ln',
      '....baskssb...ln',
      '....bbsssSb...ln',
      '...hbbbsscb...ln',
      '..hhcccccch..sln',
      '..hcnccccsnnnNln',
      '..hc.ncc.c....ln',
      '..h..cNNc.....n.',
      '.....ccYc....n..',
      '.....bb.bb......',
      '.....bb.bb......',
      '....NNN.NNN.....',
      '................',
    ],
  },
  'hero:wizard': {
    rows: [
      '......u.........',
      '.....uU.........',
      '.....uuU......f.',
      '....uuyuU....fyf',
      '....uuuuuU....f.',
      '...UUUUUUUU...n.',
      '.....sssss....n.',
      '.....skssk....n.',
      '.....sssss....n.',
      '.....wwwww...sn.',
      '....uuwwwuuuU.n.',
      '....uuuwuuu...n.',
      '....uuuuuuU...n.',
      '...uuuuuuuuU..n.',
      '...UUUUUUUUU....',
      '................',
    ],
  },
  'hero:assassin': {
    rows: [
      '................',
      '......PPPP......',
      '.....PpppPP.....',
      '.....ppkkkpP....',
      '.....pkyykp.....',
      '.....PkkkkP.....',
      '......PppP......',
      '....PpppppP.....',
      '...lPpPppPpPl...',
      '..l.spppppps.l..',
      '.....pPpPpp.....',
      '.....pppppp.....',
      '.....kk..kk.....',
      '.....kk..kk.....',
      '....kkk..kkk....',
      '................',
    ],
  },
  'hero:paladin': {
    rows: [
      '................',
      '......yyyy..YY..',
      '.....ymmmmy.YY..',
      '.....mmkkmm..n..',
      '.....mmssmm..n..',
      '......mssm...n..',
      '....UwwwwwwU.n..',
      '...UwwwyywwwsY..',
      '..yyyUwwwwwU....',
      '..ywyUwwwwwU....',
      '..yyyUwyyyw.....',
      '...y.UwwwwwU....',
      '......mm.mm.....',
      '......mm.mm.....',
      '.....MMM.MMM....',
      '................',
    ],
  },
  'hero:necromancer': {
    rows: [
      '................',
      '.....PPPPP...ww.',
      '....PPPPPPP.wkkw',
      '....PPlllPP.wwww',
      '....PltlltP..nw.',
      '....PPlllPP..n..',
      '.....PPlPP...n..',
      '....PpppppPsnn..',
      '...PpPpppPpP.n..',
      '...Pp.ppppp..n..',
      '...P..pPpPp..n..',
      '.....ppppppP.n..',
      '....pppppppP....',
      '...ppPppPppPP...',
      '...PPPPPPPPPP...',
      '................',
    ],
  },
  'hero:engineer': {
    rows: [
      '................',
      '......nnnn......',
      '.....nnnnnn.....',
      '.....dudduds....',
      '.....ssssss.....',
      '.....ssSsss.....',
      '......ssss......',
      '...ddffffff.....',
      '...ddfYffYfs.l..',
      '...ddffffff.lml.',
      '...dd.fffff..l..',
      '......fNNNf..l..',
      '......dd.dd.....',
      '......dd.dd.....',
      '.....kkk.kkk....',
      '................',
    ],
  },
  'hero:monk': {
    rows: [
      '................',
      '......ssss......',
      '.....ssssss.....',
      '.....sskssk.....',
      '.....ssssss.....',
      '......sSSs......',
      '.......ss.......',
      '....ttTttTtt....',
      '...sttyyyyttts..',
      '..ss.ttTTtt..ss.',
      '.....tNNNNt.....',
      '.....tttttt.....',
      '.....ttt.ttt....',
      '.....ss...ss....',
      '....sss...sss...',
      '................',
    ],
  },

  /* ------------------------------------------------------------ enemies */
  slime: {
    palette: { a: '#7ed957', b: '#4ea83a', c: '#2f6e24' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '.......aa.......',
      '.....aaaaaa.....',
      '....aawaaaaa....',
      '...aawwaaaaaa...',
      '...aaaaaaaaaab..',
      '..aaakaaaakaabb.',
      '..aaaaaaaaaaabb.',
      '..baaaaaaaaaabb.',
      '...bbbbbbbbbbb..',
      '....cccccccccc..',
    ],
  },
  rat: {
    palette: { a: '#8c8478', b: '#5f584f', e: '#ff4d4d' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '..........bb....',
      '.........baab...',
      '....aaaaaaaaeab.',
      '..aaaaaaaaaaaaar',
      '.aabaaaaaaaaaa..',
      'n.bbbaaaabbb....',
      '.n..bb...bb.....',
      '..nn.b....b.....',
      '................',
    ],
  },
  ratKing: {
    palette: { a: '#8c8478', b: '#5f584f', e: '#ff4d4d' },
    rows: [
      '................',
      '..........y.y.y.',
      '..........yyyyy.',
      '..........baab..',
      '.........baaaab.',
      '.........aaaeaab',
      '....aaaaaaaaaaar',
      '..aaRRRRRaaaaa..',
      '.aaRrrrrrRaaaa..',
      '.abRrryrrRaab...',
      'n.bRrrrrrRbbb...',
      '.n.RRRRRRR......',
      '..n.bb...bb.....',
      '....bb...bb.....',
      '...bbb..bbb.....',
      '................',
    ],
  },
  skeleton: {
    palette: { a: '#e8e2cf', b: '#a39c86' },
    rows: [
      '................',
      '......aaaa......',
      '.....aaaaaa.....',
      '.....akaaka.....',
      '.....aaaaaa.....',
      '......akka......',
      '.......aa.......',
      '....bb.aa.bb....',
      '...b..baab..b...',
      '...b..abab..bl..',
      '......abab...l..',
      '.......aa....l..',
      '......a..a...n..',
      '......a..a......',
      '.....aa..aa.....',
      '................',
    ],
  },
  skeletonArcher: {
    palette: { a: '#e8e2cf', b: '#a39c86' },
    rows: [
      '................',
      '......aaaa...n..',
      '.....aaaaaa...n.',
      '.....akaaka...ln',
      '.....aaaaaa...ln',
      '......akka....ln',
      '.......aa.....ln',
      '....bb.aa.bbbaln',
      '...b..baab....ln',
      '...b..abab....ln',
      '......abab....n.',
      '.......aa....n..',
      '......a..a......',
      '......a..a......',
      '.....aa..aa.....',
      '................',
    ],
  },
  goblin: {
    palette: { a: '#8fc25a', b: '#5e8c34', h: '#6b4a2b' },
    rows: [
      '................',
      '................',
      '...b........b...',
      '...ab.aaaa.ba...',
      '....aaaaaaaa....',
      '.....akaaka.....',
      '.....aaaaaa.....',
      '......awwa......',
      '.......aa.......',
      '.....hhhhhh.....',
      '....ahhhhhha.l..',
      '....a.hhhh..al..',
      '......hhhh...n..',
      '......aa.aa.....',
      '.....hhh.hhh....',
      '................',
    ],
  },
  goblinShaman: {
    palette: { a: '#7fb04e', b: '#557a30', h: '#5a2d6b' },
    rows: [
      '.....r.y.u......',
      '.....ryyuu...t..',
      '...b.aaaaa.bttt.',
      '...ab.aaaa.ba.n.',
      '....aaaaaaaa..n.',
      '.....akaaka...n.',
      '.....aaaaaa...n.',
      '......awwa....n.',
      '.......aa.....n.',
      '.....hhhhhh..an.',
      '....ahhyyhhha.n.',
      '....a.hhhhh...n.',
      '.....hhhhhh.....',
      '.....hhhhhhh....',
      '....hhhhhhhhh...',
      '................',
    ],
  },
  mushroom: {
    palette: { a: '#6a7ad9', b: '#4a56a6', c: '#e8dcc0', d: '#b8ab8e' },
    rows: [
      '................',
      '................',
      '.....aaaaaa.....',
      '...aawaaaaaaa...',
      '..aawwaaaawaaa..',
      '..aaaaaaawwaaa..',
      '.aawaaaaaaaaaab.',
      '.abbbbbbbbbbbbb.',
      '....cccccccc....',
      '....ckcccckc....',
      '....cccccccc....',
      '....cccRRccc....',
      '....cccccccc....',
      '.....cccccc.....',
      '....ddd..ddd....',
      '................',
    ],
  },
  mushroomBoss: {
    palette: { a: '#b04ad9', b: '#7a2da6', c: '#e8dcc0', d: '#8a7a5e', e: '#9dff5a' },
    rows: [
      '................',
      '.....aaaaaa.....',
      '...aawaaaawaa...',
      '..aawwaaaaaaaa..',
      '.aaaaaaawwaaaaa.',
      '.awaaaaaaaaaawa.',
      'abbbbbbbbbbbbbbb',
      '...cccccccccc...',
      '...ccekcceckc...',
      '...cccccccccc...',
      '...ccc.kk.ccc...',
      '...cccccccccc...',
      '..dcccccccccd...',
      '.d.dccccccd.d...',
      'd...dddddd...d..',
      '................',
    ],
  },
  bat: {
    palette: { a: '#5a4470', b: '#3a2a4a', e: '#ff4d4d' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      'b.............b.',
      'bb....a..a...bb.',
      'bbb..aaaaaa.bbb.',
      'bbbbaaeaaeaabbb.',
      '.bbbaaaaaaaabbb.',
      '..bb.aawwaa.bb..',
      '...b..aaaa..b...',
      '.......aa.......',
      '................',
      '................',
      '................',
    ],
  },
  zombie: {
    palette: { a: '#8fb08a', b: '#5e7a5a', h: '#4a3a2a' },
    rows: [
      '................',
      '......hhhh......',
      '.....hhaaah.....',
      '.....aakaak.....',
      '.....aaaaaa.....',
      '......aRRa......',
      '......aaaa......',
      '....uuUuuUuu....',
      '...aauUuuUuaaaa.',
      '..aa.uuuuuu...a.',
      '.....uUuuUu.....',
      '.....uuuuuu.....',
      '.....nn..nn.....',
      '.....aa..aa.....',
      '....aaa..aaa....',
      '................',
    ],
  },
  cultist: {
    palette: { a: '#6b2a3a', b: '#4a1a28', e: '#ffd35a', s: '#d9c3a0' },
    rows: [
      '................',
      '......aaaa......',
      '.....aaaaaa.....',
      '.....abkkkaa....',
      '.....akekeka....',
      '.....abkkkaa....',
      '......aaaa......',
      '.....aaaaaaa....',
      '....aaabbaaas...',
      '....aa.abba.ss..',
      '....a..abba.....',
      '.....aabbaa.....',
      '....aaabbaaa....',
      '...aaaabbaaaa...',
      '...bbbbbbbbbb...',
      '................',
    ],
  },
  knight: {
    palette: { a: '#d8d2bd', b: '#a39c86', c: '#6d6755', e: '#ff5d5d' },
    rows: [
      '................',
      '......aaaa......',
      '.....aaaaaa.....',
      '.....aceeca.....',
      '.....aaaaaa.....',
      '......bbbb......',
      '....abaaaaba..l.',
      '...abaaaaaaba.l.',
      '...c.aaccaa.a.l.',
      '..cccaaaaaacc.l.',
      '..cec.aaaaaa.yyy',
      '..ccc.bbbbbb..n.',
      '...c..aa..aa....',
      '......aa..aa....',
      '.....bbb..bbb...',
      '................',
    ],
  },
  golem: {
    palette: { a: '#9c9484', b: '#6f685a', c: '#4a453b', e: '#7ad0ff' },
    rows: [
      '................',
      '................',
      '.....bbbbbb.....',
      '....baaaaaab....',
      '....aaeaaeaa....',
      '....aaaaaaaa....',
      '..bbbbaaaabbbb..',
      '.baaabbbbbbaaab.',
      '.baabaaaaaabaab.',
      '.baabaacaaabaab.',
      '.bbb.baaaab.bbb.',
      '.cc..bbbbbb..cc.',
      '.....bb..bb.....',
      '....aab..baa....',
      '....ccc..ccc....',
      '................',
    ],
  },
  spider: {
    palette: { a: '#5a4a3a', b: '#3a2e24', e: '#ff4d4d', c: '#8a6a4a' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '....b......b....',
      '...b.b.aa.b.b...',
      '..b...aaca...b..',
      '.b...aaaaaa...b.',
      'b...baaaaaab...b',
      '...b.aeaaea.b...',
      '..b..aaaaaa..b..',
      '.b....abba....b.',
      'b.............b.',
      '................',
      '................',
    ],
  },
  beetle: {
    palette: { a: '#8fe3ff', b: '#4fb3d9', c: '#2a7aa0', e: '#ffffff' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.......cc.......',
      '......cabc......',
      '....caaabbbc....',
      '...caaawabbbc...',
      '..caawaaaabbbc..',
      '..caaaaaaaabbbck',
      '..cbbbbbbbbbbcke',
      '...cc.c..c.cck..',
      '..c...c..c...c..',
      '................',
      '................',
      '................',
    ],
  },
  wolf: {
    palette: { a: '#8a8f99', b: '#5f636b', e: '#ffd35a' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '..........a..a..',
      '.........aaaaa..',
      '.b......aaaeaa..',
      '.bb....aaaaaaaak',
      '..baaaaaaaaaaww.',
      '...aaaaaaaaaa...',
      '...aabbbbbaab...',
      '...a.b...a..b...',
      '..aa.bb.aa..bb..',
      '................',
      '................',
    ],
  },
  orc: {
    palette: { a: '#6f9a3a', b: '#4b6b26', h: '#6b4a2b', m: '#b8b8b8' },
    rows: [
      '................',
      '......aaaa......',
      '.....aaaaaa.....',
      '.....aeaaea.....',
      '.....aaaaaa.....',
      '.....awaawa.....',
      '......aaaa......',
      '...hhhhhhhhh....',
      '..aahhmhhhhaa...',
      '..aa.hhhhhh.aa..',
      '..a..hhhhhh..am.',
      '.....hhhhhh..mmm',
      '.....hh..hh..mmm',
      '.....aa..aa..n..',
      '....hhh..hhh....',
      '................',
    ],
  },
  mage: {
    palette: { a: '#3b2d5a', b: '#241a3a', e: '#b38cff' },
    rows: [
      '......a.........',
      '.....ab.........',
      '.....aab......e.',
      '....aaaab....eee',
      '....aaaaab....e.',
      '...bbbbbbbb...n.',
      '.....kkkkk....n.',
      '.....keeke....n.',
      '.....kkkkk....n.',
      '....aaaaaaa..sn.',
      '....aabaaaab..n.',
      '....aaabaaa...n.',
      '....aaaaaaab..n.',
      '...aaaaaaaaab...',
      '...bbbbbbbbbb...',
      '................',
    ],
  },
  gargoyle: {
    palette: { a: '#8c8f99', b: '#5f636b', c: '#3b3e45', e: '#ffcf5a' },
    rows: [
      '................',
      '................',
      '.b..........b...',
      '.bb..a..a..bb...',
      '.bbb.aaaa.bbb...',
      '.bbbbaeeabbbb...',
      '..bbbaaaabbb....',
      '....aawwaa......',
      '...aa.aaaa.a....',
      '...a..aaaa..a...',
      '.....aaaaaa.....',
      '.....aa..aa.....',
      '....cc....cc....',
      '................',
      '................',
      '................',
    ],
  },
  kobold: {
    palette: { a: '#d9743a', b: '#a3502a', h: '#6b4a2b' },
    rows: [
      '................',
      '................',
      '...........yf...',
      '..........k.....',
      '.........kkk....',
      '......aa.kkk....',
      '.....aaaa.......',
      '.....akaaaa.....',
      '.....aaaaaaw....',
      '......aaa.......',
      '.....hhhhh......',
      '....aahhhhaa....',
      '......hhh.......',
      '......a.a.......',
      '.....aa.aa......',
      '................',
    ],
  },
  imp: {
    palette: { a: '#d9452a', b: '#8a2a1a', e: '#ffd35a' },
    rows: [
      '................',
      '................',
      '....y......y....',
      '....ya....ay....',
      '.....aaaaaa.....',
      '.....aeaaea.....',
      '..b..aaaaaa..b..',
      '.bbb..awwa..bbb.',
      '.bbbbaaaaaabbbb.',
      '..bb.aaaaaa.bb..',
      '.....aaaaaa.....',
      '......a..a......',
      '.....aa..aa..a..',
      '..........aaa...',
      '................',
      '................',
    ],
  },
  ghost: {
    palette: { a: '#cfe3f0', b: '#8aa3b8', e: '#6cf0c2' },
    rows: [
      '................',
      '.....aaaaa......',
      '....aaaaaaa.....',
      '...aakaaakaa....',
      '...aaeaaaeaa....',
      '...aaakkkaaa....',
      '...aaaaaaaaa....',
      '..aaaaaaaaaaa...',
      '..aaaaaaaaaaa.a.',
      '.aa.aaaaaaaaaa..',
      '....aaaaaaaa....',
      '....aaabaaba....',
      '.....ab.ab.a....',
      '......b...b.....',
      '................',
      '................',
    ],
  },
  eye: {
    palette: { a: '#8a3a6a', b: '#5a2446', e: '#ff4d4d' },
    rows: [
      '................',
      '................',
      '.....aaaaaa.....',
      '....awwwwwwa....',
      '...awwwwwwwwa...',
      '..awwweeeewwwa..',
      '..awweekkeewwa..',
      '..awweekkeewwa..',
      '..awwweeeewwwa..',
      '...awwwwwwwwa...',
      '....aawwwwaa....',
      '.....aaaaaa.....',
      '.....b.b.b.b....',
      '....b.b.b.b.....',
      '.....b...b......',
      '................',
    ],
  },
  demon: {
    palette: { a: '#b8321f', b: '#6a1a12', e: '#ffd35a' },
    rows: [
      '..y..........y..',
      '..yy.......yy...',
      '...yaaaaaaay....',
      '...aaeaaaeaa....',
      '.b.aaaaaaaaa.b..',
      'bb..aakkkaa..bb.',
      'bbb.aawwwaa.bbbb',
      'bbbbbaaaaaaabbbb',
      'bb.aaaaaaaaaa.bb',
      'b..aa.aaaaa.aa.b',
      '...a..aaaaa..a..',
      '.....aaaaaaa....',
      '.....aa...aa....',
      '.....aa...aa....',
      '....yyy...yyy...',
      '................',
    ],
  },
  troll: {
    palette: { a: '#5a8a8a', b: '#3a5e5e', h: '#6b4a2b' },
    rows: [
      '................',
      '.....aaaa.......',
      '....aaaaaa......',
      '....aeaaea......',
      '....aaaaaa......',
      '....awaawa......',
      '...aaaaaaaa.nn..',
      '..aaabaaaabannn.',
      '..aa.aaaaaa.nnn.',
      '..aa.aaaaaa..n..',
      '..a..hhhhhh..n..',
      '.....hhhhhh.....',
      '.....aa..aa.....',
      '.....aa..aa.....',
      '....aaa..aaa....',
      '................',
    ],
  },
  lich: {
    palette: { a: '#4a3a6a', b: '#2a1f40', e: '#6cf0c2', s: '#e8e2cf' },
    rows: [
      '................',
      '.....y.y.y......',
      '.....yyyyy...e..',
      '.....sssss..eee.',
      '.....sesesk..e..',
      '.....sssss...s..',
      '......sks....s..',
      '....aaaaaaa..s..',
      '...aabaaabaa.s..',
      '..sa.aaaaa.ass..',
      '..s..abaaba..s..',
      '.....aaaaaa..s..',
      '....aaaaaaaa.s..',
      '...aaabaabaaa...',
      '...bbbbbbbbbb...',
      '................',
    ],
  },
  dragon: {
    palette: { a: '#6a5a5a', b: '#3a2e2e', c: '#c9a07a', e: '#ffcf5a', f: '#ff8a2a' },
    rows: [
      '........................',
      '...............bb.......',
      '..............baab......',
      '.......b.....baaaab.....',
      '......bb....baaaaaab....',
      '.....bbb...baaaaeaaab...',
      '....bbbb..baaaaaaaaaww..',
      '...bbbbbb.aaaaaacccccc..',
      '..bbbbbbbaaaaaa..wwww...',
      '.bbbbbbbaaaaaa..........',
      'bbbbbbaaaaaaaaa.........',
      '.....aaaacccaaa.........',
      '....aaaaccccaaaa........',
      '...aaa.acccca.aaa.......',
      '..aa...aaaaaa...a.......',
      '.aa....aa..aa...........',
      'a.....bbb..bbb..........',
      '........................',
    ],
  },

  /* ------------------------------------------------------------ allies */
  turret: {
    palette: { a: '#a4adbf', b: '#5f6b78', e: '#ff8a2a' },
    rows: [
      '................',
      '................',
      '................',
      '................',
      '................',
      '................',
      '......aaa.......',
      '.....aaaaabbbb..',
      '.....aaeaabbbb..',
      '.....aaaaa......',
      '......bbb.......',
      '.....bbbbb......',
      '....aaaaaaa.....',
      '....bbbbbbb.....',
      '...aaaaaaaaa....',
      '...bbbbbbbbb....',
    ],
  },
  tesla: {
    palette: { a: '#a4adbf', b: '#5f6b78', e: '#8fd3ff' },
    rows: [
      '.......e........',
      '......eee.......',
      '.......e........',
      '......bbb.......',
      '.....aaaaa......',
      '......bbb.......',
      '.....aaaaa......',
      '......bbb.......',
      '.....aaaaa......',
      '......bbb.......',
      '......bbb.......',
      '.....bbbbb......',
      '....aaaaaaa.....',
      '....bbbbbbb.....',
      '...aaaaaaaaa....',
      '...bbbbbbbbb....',
    ],
  },
  barrel: {
    rows: [
      '................',
      '................',
      '................',
      '................',
      '.....NNNNNN.....',
      '....nnnnnnnn....',
      '....NNNNNNNN....',
      '....nnryrynn....',
      '....nnyryrnn....',
      '....nnryrynn....',
      '....NNNNNNNN....',
      '....nnnnnnnn....',
      '....nnnnnnnn....',
      '....NNNNNNNN....',
      '.....nnnnnn.....',
      '................',
    ],
  },
  mech: {
    palette: { a: '#a4adbf', b: '#5f6b78', e: '#ff8a2a' },
    rows: [
      '................',
      '.....aaaaaa.....',
      '....abeeeeba....',
      '....aaaaaaaa....',
      '..bb.aaaaaa.bb..',
      '.baabbbbbbbaab..',
      '.baaaaaaaaaaab..',
      '.baa.aaeeaa.aab.',
      '..bb.aaaaaa..bb.',
      '.....bbbbbb.....',
      '....aa....aa....',
      '....aa....aa....',
      '...baa....aab...',
      '...bbb....bbb...',
      '................',
      '................',
    ],
  },
};
